# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'


# Use config.yml for basic VM configuration.
require 'yaml'
if !File.exist?('../../config.yml')
  raise 'Configuration file not found! Please copy example.config.yml to config.yml and try again.'
end
vconfig = YAML::load_file("../../config.yml")

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "example.dev" do |a|
    a.vm.provider "docker" do |d|

      d.build_dir = "."
      d.ports = ["8080:8080", "80:80"]
      d.name = "example"
      d.has_ssh = true
    end
    a.vm.hostname = "example.docker"

    # a.vm.synced_folder "../../../../../", "/home/vagrant/example"

    for synced_folder in vconfig['vagrant_synced_folders'];
      a.vm.synced_folder synced_folder['local_path'], synced_folder['destination'],
        type: synced_folder['type'],
        id: synced_folder['id'],
        create: synced_folder.include?('create') ? synced_folder['create'] : false
    end

    a.ssh.port = 22
    a.vm.provision "ansible" do |ansible|
      ansible.playbook = "../../playbook.yml"
      ansible.inventory_path = "inventory"
      ansible.verbose = 'vvvv'
      #ansible.start_at_task = "Check if Drupal is booting."
    end
  end
end
